# Generated by Django 6.1 on 2026-08-31 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Nombre del estudiante', max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(help_text='Apellido del estudiante', max_length=100, verbose_name='Apellido')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'student',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Nombre del docente', max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(help_text='Apellido del docente', max_length=100, verbose_name='Apellido')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'teacher',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del curso o asignatura', max_length=150, verbose_name='Nombre de la Asignatura')),
                ('teacher', models.ForeignKey(db_column='teacher_id', help_text='Profesor que imparte la asignatura', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academic.teacher', verbose_name='Docente Asignado')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'db_table': 'course',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic.course', verbose_name='Asignatura')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'student_course',
                'ordering': ['id'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
