# Generated by Django 6.1 on 2026-09-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='modality',
            field=models.CharField(choices=[('P', 'Presencial'), ('O', 'Online / Virtual'), ('H', 'Híbrida')], default='P', help_text='Modalidad de impartición de la materia', max_length=1, verbose_name='Modalidad'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', help_text='Género del estudiante', max_length=1, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACT', 'Alumno Regular'), ('SUS', 'Suspendido'), ('EGR', 'Egresado')], default='ACT', help_text='Estado actual de la matrícula', max_length=3, verbose_name='Estado Académico'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='degree',
            field=models.CharField(choices=[('LIC', 'Licenciado(a)'), ('MAG', 'Magíster'), ('DOC', 'Doctor(a) / Ph.D.')], default='MAG', help_text='Nivel o grado académico del docente', max_length=3, verbose_name='Grado Académico'),
        ),
    ]
